/*

Gene Drumheller
    
Problem 002
    
    

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


*/


#include <iostream>


int main() {

    const unsigned MAX = 4000000;
    unsigned fib1 = 1;
    unsigned fib2 = 2;
    unsigned temp = 0;
    unsigned sum = 0;
    
    while (fib2 < MAX) {
    
        if (fib2 % 2 == 0)
            sum += fib2;
            
        temp = fib2 + fib1;
        fib1 = fib2;
        fib2 = temp;
    
    }
    
    std::cout << "Sum = " << sum << std::endl;


    return 0;
}












